version: '3'

services:
  server:
    build: ./Java
    image: java
    ports: 
    - "8080:8080"
    environment:
      allowed.origins : http://localhost:3000
    networks:
      - project
  client:
    build: ./React_files/demo_app
    image: react
    ports:
    - "3000:3000"
    networks:
      - project

networks:
  project:
    driver: bridge