version: '3'

services:
  server:
    build: ./Java
    # image: java (Build will link it)
    ports: 
    - ${SERVERPORT}:${SERVERPORT}
    networks:
      - project

  client:
    build: ./React_files/demo_app
    # image: react (Build will link it)
    ports:
    - ${CLIENTPORT}:${CLIENTPORT}
    networks:
      - project

networks:
  project:
    driver: bridge